# Development service docker compose script

services:
  doc_label:
    image: doc-label:latest
    build:
      context: .

    command:
      # Run uvicorn with these extra args
      - "--host=0.0.0.0"
      - "--port=8000"
      - "--timeout-graceful-shutdown=10"
      - "--log-level=info"
      - "--log-config=/config/log-config.conf"

    ports:
      - "8000:8000"

    volumes:
      - "./config/:/home/appuser/config"
      - "./logs/:/home/appuser/logs"
